### ISSUE TITLE
请问研究生抢讲座的脚本结合起来要怎么搞

### ISSUE THREAD

**Issue by luowl123** [Golevka2001/SEU-Auth#1]
请问研究生抢讲座的脚本结合起来要怎么搞，例如这个抢课的脚本https://github.com/zhjcreator/fetch_lecture，他这里的登录应该是过时了，我换成了你这里的，登录成功了，当时抢课脚本有问题，大佬帮忙看看

**Comment by Golevka2001** [comment]
不好意思我明年才研一😂现在访问不了这个应用，不太了解该应用具体的登录流程，所以以下回复仅供参考。

读了一下 [@zhjcreator/fetch_lecture](https://github.com/zhjcreator/fetch_lecture)，大致流程是：

1. 调用 `login()` 登录综合服务大厅，得到成功登录后的 session；
2. 调用 `get_lecture_list()` 使用上一步的 session 获取讲座列表；
3. 调用 `fetch_lecture()` 提交 post 请求；

推测只是第一步由于认证系统换新出问题，请您先做以下尝试：

将下面的代码替换本仓库 [seu_auth.py](https://github.com/Golevka2001/SEU-Auth/blob/main/seu_auth.py) 中 `if __name__ == '__main__'` 下的原内容：

```python
username = '【填入您的一卡通号】'
password = '【填入您的密码】'
service_url = 'http://ehall.seu.edu.cn/gsapp/sys/jzxxtjapp/*default/index.do'
session, redirect_url = seu_login(username, password, service_url)
res = session.get(redirect_url)
res = session.post("http://ehall.seu.edu.cn/gsapp/sys/jzxxtjapp/modules/hdyy/hdxxxs.do", data={"pageSize": 12, "pageNumber": 1})
print(res.json())
```

执行 `python seu_auth.py`，观察是否能够获取到讲座列表，以便提供接下来的帮助。

**Comment by luowl123** [comment]
感谢大佬回复！！
按照你说的改法可以成功拿到数据！
不过这个库[@zhjcreator/fetch_lecture](https://github.com/zhjcreator/fetch_lecture)里面的接口都过时了需要重新对一遍才行。

**Comment by Golevka2001** [comment]
好的，不客气。
